POST http://localhost:3000/api/auth/signup
Content-Type: application/json

{
  "email": "testuser1@example.com",
  "nickname": "testuser1",
  "password": "testpassword"
}


###

POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "testuser1@example.com",
  "nickname": "testuser1",
  "password": "testpassword"
}

###

POST http://localhost:3000/api/auth/logout

###

POST http://localhost:3000/api/auth/refresh
Content-Type: application/json


###

GET http://localhost:3000/api/posts

### 

POST http://localhost:3000/api/posts
Content-Type: application/json

{
  "title": "새로운 게시글 제목",
  "content": "Hello, world!"
}


###

PATCH http://localhost:3000/api/posts/1
Content-Type: application/json

{
  "title": "수정된 게시글 제목",
  "content": "내용도 수정했습니다."
}



###

DELETE http://localhost:3000/posts/1

